export default {
  login: 'NgocTheNguyen',
  id: 86214462,
  node_id: 'MDQ6VXNlcjg2MjE0NDYy',
  avatar_url: 'https://avatars.githubusercontent.com/u/86214462?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/NgocTheNguyen',
  html_url: 'https://github.com/NgocTheNguyen',
  followers_url: 'https://api.github.com/users/NgocTheNguyen/followers',
  following_url:
    'https://api.github.com/users/NgocTheNguyen/following{/other_user}',
  gists_url: 'https://api.github.com/users/NgocTheNguyen/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/NgocTheNguyen/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/NgocTheNguyen/subscriptions',
  organizations_url: 'https://api.github.com/users/NgocTheNguyen/orgs',
  repos_url: 'https://api.github.com/users/NgocTheNguyen/repos',
  events_url: 'https://api.github.com/users/NgocTheNguyen/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/NgocTheNguyen/received_events',
  type: 'User',
  site_admin: false,
  name: 'Nguyen Ngoc The',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 11,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2021-06-21T02:27:54Z',
  updated_at: '2021-09-15T00:48:57Z',
};
